version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    groups:
      npm-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
