{
 "title": "Fabric",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Join Channel",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(peer_join_channel_time_seconds)"
    }
   ]
  },
  {
   "title": "Install Chaincode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(peer_install_chaincode_time_seconds)"
    }
   ]
  },
  {
   "title": "Instantiate Chaincode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(peer_instantiate_chaincode_time_seconds)"
    }
   ]
  },
  {
   "title": "Upgrade Chaincode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(peer_upgrade_chaincode_time_seconds)"
    }
   ]
  },
  {
   "title": "Invoke Chaincode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(peer_invoke_chaincode_time_seconds)"
    }
   ]
  },
  {
   "title": "Query Chaincode",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name)(peer_query_chaincode_time_seconds)"
    }
   ]
  },
  { "title": "peer0-org1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"fabric-net\",pod_name=~\"peer0-org1.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"fabric-net\",pod_name=~\"peer0-org1.*\"})/1024^2"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total{namespace=\"fabric-net\",pod_name=~\"peer0-org1.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"fabric-net\",pod_name=~\"peer0-org1.*\"}[3m])))/1024"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "WARN AND kubernetes.namespace_name=fabric-net AND kubernetes.container_name=peer0-org1",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "peer1-org1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"fabric-net\",pod_name=~\"peer1-org1.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"fabric-net\",pod_name=~\"peer1-org1.*\"})/1024^2"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total{namespace=\"fabric-net\",pod_name=~\"peer1-org1.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"fabric-net\",pod_name=~\"peer1-org1.*\"}[3m])))/1024"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "WARN AND kubernetes.namespace_name=fabric-net AND kubernetes.container_name=peer1-org1",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "peer0-org2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"fabric-net\",pod_name=~\"peer0-org2.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"fabric-net\",pod_name=~\"peer0-org2.*\"})/1024^2"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total{namespace=\"fabric-net\",pod_name=~\"peer0-org2.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"fabric-net\",pod_name=~\"peer0-org2.*\"}[3m])))/1024"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "WARN AND kubernetes.namespace_name=fabric-net AND kubernetes.container_name=peer0-org2",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "peer1-org2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"fabric-net\",pod_name=~\"peer1-org2.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"fabric-net\",pod_name=~\"peer1-org2.*\"})/1024^2"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 40 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total{namespace=\"fabric-net\",pod_name=~\"peer1-org2.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"fabric-net\",pod_name=~\"peer1-org2.*\"}[3m])))/1024"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "WARN AND kubernetes.namespace_name=fabric-net AND kubernetes.container_name=peer1-org2",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Orderer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"fabric-net\",pod_name=~\"orderer.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"fabric-net\",pod_name=~\"orderer.*\"})/1024^2"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(container_network_transmit_bytes_total{namespace=\"fabric-net\",pod_name=~\"orderer.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{namespace=\"fabric-net\",pod_name=~\"orderer.*\"}[3m])))/1024"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "WARN AND kubernetes.namespace_name=fabric-net AND kubernetes.container_name=orderer",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}